# -*- coding: utf-8 -*-
"""Atividade N2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m4QpzbH6jMyNUaJAY0hD0IPjJQeG05xL
"""

sala = []
while True: 
    acao = int(input('''Digite 1 para adicionar um aluno
    2 para excluir um aluno
    3 para atualizar o aluno
    4 para ver a lista de alunos '''))
    if acao == 1:
        aluno = input('informe o nome do aluno')
        sala.append(aluno)
    elif acao == 2:
        aluno = input('informe o alno que deseja excluir!')
        if aluno in sala:
            aluno_x = sala.index(aluno)
            sala.pop(aluno_x)
            print(f'{aluno}excluido(a)com suceso.')
        else:
            print('o aluno não está cadastrado.')
    elif acao == 3:
        aluno = input('informe o nome do aluno: ')
        if aluno in sala:
            aluno_x = sala.index(aluno)
            sala.pop(aluno_x)
            aluno = input('informe o nome do aluno:')
            sala.insert(aluno_x,aluno)
            print(f'{aluno} foi adicionado com sucesso.')
            sala.sport()
        else:
            print('o aluno não está cadastrado')
    elif acao == 4:
        print(sala)
    elif acao == 5:
        break
    else: 
        print('Opção inválida')

sala